name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-04-09"

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "a1c1a63a-6ef5-4e6d-8e8c-b6d9e8feb810"

[[kv_namespaces]]
binding = "kv"
id = "2io01d4b299e481b9de060ece9e7785c"

#[[r2_buckets]]
#binding = ""
#bucket_name = ""

[assets]
binding = "assets"
directory = "./dist"

[vars]
domain = ["example.com", "example2.com"]
admin = "admin@example.com"
jwt_secret = "K8x@r!3XqZ7#bLm$9pV&yTfC1W*sD2Nv%Q@4Zh^gRb6&UsP!m"
r2_domain = ""
site_key = ""
secret_key = ""
