name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
domain = ["xxxxx", "xxxxx"]
admin = "xxxxx@xxxxx"
r2_domain = "xxxxx"
jwt_secret = "xxxxx"
site_key = "xxxxx"
secret_key = "xxxxx"
