name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-04-09"

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = ""

[[kv_namespaces]]
binding = "kv"
id = ""

[[r2_buckets]]
binding = "r2"
bucket_name = "email"

[vars]
domain = ["", ""]
admin = ""
r2_domain = ""
jwt_secret = ""
site_key = ""
secret_key = ""
